# Generated by Django 5.0.4 on 2024-05-06 09:18

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("customer", "Customer"),
                            ("delivery", "Delivery Personnel"),
                            ("restaurant", "Restaurant Owner"),
                        ],
                        max_length=20,
                    ),
                ),
                ("full_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("phone_number", models.CharField(max_length=20)),
                ("address", models.TextField()),
                ("username", models.CharField(max_length=50, unique=True)),
                ("password", models.CharField(max_length=100)),
                (
                    "vehicle_type",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "vehicle_plate_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "restaurant_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
        ),
    ]
